spring:
  application:
    name: atlas-knowledge-base
  profiles:
    default: local
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
