spring:
  application:
    name: atlas-knowledge-base
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
